<?php
require '../vendor/autoload.php';
use Dompdf\Dompdf;

function pdf_downloader($html){
     
    $dompdf = new Dompdf();
    
    $dompdf->loadHtml($html);
    $dompdf->setPaper('A4', 'landscape');
    $dompdf->render();
    $dompdf->stream();
    $pdf = $dompdf->output();

}



$html = '<h1 style="color:blue;">Hello World>> changed s!</h1><p>A PDF generated by DomPDF library.</p>';
pdf_downloader($html);